version: '3'
services:
  back:
    image: sikgates/tegen:latest
    container_name: tegen-back
    ports:
      - "5001:5001"
    environment:
      - TZ=Etc/UTC
      - REDIS_HOST=redis-14438.c281.us-east-1-2.ec2.redns.redis-cloud.com
      - REDIS_PORT=14438
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=AoWvAXv3JTPRBrgwxRX58G9AVxFhQzpj
    networks:
      - app_network
    restart: always

  db:
    image: mariadb:11.4      
    container_name: tegen-db  
    restart: always
    environment:

      MYSQL_ROOT_PASSWORD: ktcpw123   
      MYSQL_DATABASE: kakaotechcampus123
      MYSQL_USER: kakaotechadmin123                     
      MYSQL_PASSWORD: password1234         
    volumes:
      - mariadb_data:/var/lib/mysql 
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mariadb_data: